---
driver:
  name: docker
driver_config:
  require_chef_omnibus: 12.4.1
  use_sudo: false
  privileged: true # shibd silently fails without priv container!

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

dns:
  - 8.8.8.8
  - 8.8.4.4

suites:
  - name: default
    run_list: ['shib_oauth2_bridge_test::default']